=== doriveramirez/Actividad6/Politica.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.David.com/Politica"
           xmlns="https://www.David.com/Politica"
           elementFormDefault="qualified">

    <xs:element name="contactos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contacto" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="contacto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="datosUsuario"/>
                <xs:element ref="datosInformacion"/>
            </xs:sequence>
            <xs:attribute name="motivo" type="motivoTipo"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="datosUsuario">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre"/>
                <xs:element ref="apellidos"/>
                <xs:element ref="edad"/>
                <xs:element ref="email"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="apellidos" type="xs:string"/>
    <xs:element name="edad" type="xs:int"/>
    <xs:element name="email" type="xs:string"/>
    
    <xs:element name="datosInformacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="partidoPolitico"/>
                <xs:element ref="descripcion"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="partidoPolitico" type="xs:string"/>
    <xs:element name="descripcion" type="xs:string"/>
    
    <xs:simpleType name="motivoTipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="nuevaInformacion"/>
            <xs:enumeration value="sugerencia"/>
            <xs:enumeration value="queja"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="casosCorrupcion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="casoCorrupcion" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="casoCorrupcion">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id"/>
                <xs:element ref="datos"/>
                <xs:element ref="informacion"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="id" type="xs:int"/>
    
    <xs:element name="datos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="partido"/>
                <xs:element ref="lugar"/>
                <xs:element ref="costeAproximado"/>
                <xs:element ref="implicados"/>
                <xs:element ref="anoHechos"/>
                <xs:element ref="estado"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="partido" type="xs:string"/>
    <xs:element name="lugar" type="xs:string"/>
    <xs:element name="costeAproximado" type="xs:int"/>
    <xs:element name="implicados" type="xs:int"/>
    <xs:element name="anoHechos" type="xs:int"/>
    <xs:element name="estado" type="xs:string"/>
    
    <xs:element name="informacion" type="xs:string"/>
    
</xs:schema>

=== doriveramirez/Actividad6/Contactar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<contactos xmlns="https://www.David.com/Politica"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://www.David.com/Politica Politica.xsd">
    <contacto motivo="queja">
        <datosUsuario>
            <nombre>Roberto</nombre>
            <apellidos>Ascanio Falcón</apellidos>
            <edad>28</edad>
            <email>hola@gmail.com</email>
        </datosUsuario>
        <datosInformacion>
            <partidoPolitico>PP</partidoPolitico>
            <descripcion>
                La información adjuntada en el Caso Pokemon no es del todo correcta,
                presentan financiación distinta a la real.
            </descripcion>
        </datosInformacion> 
    </contacto>
    <contacto motivo="nuevaInformacion">
        <datosUsuario>
            <nombre>David</nombre>
            <apellidos>Orive Ramírez</apellidos>
            <edad>21</edad>
            <email>adios@gmail.com</email>
        </datosUsuario>
        <datosInformacion>
            <partidoPolitico>PSOE</partidoPolitico>
            <descripcion>
                El juez Javier Alba afirma que hay indicios claros de que Antonio Gutiérrez Limones, 
                portavoz de la Comisión de Exteriores en el Congreso del PSOE 
                ha podido cometer delitos de prevaricación, falsedad documental y malversación de caudales públicos.
                Gutiérrez Limones, hombre de Susana Díaz en la cámara, no ha comunicado aún su renuncia.
            </descripcion>
        </datosInformacion> 
    </contacto>
    <contacto motivo="sugerencia">
        <datosUsuario>
            <nombre>Juanmi</nombre>
            <apellidos>Pérez Gutierrez</apellidos>
            <edad>35</edad>
            <email>buenas@gmail.com</email>
        </datosUsuario>
        <datosInformacion>
            <partidoPolitico>Podemos</partidoPolitico>
            <descripcion>
                Debería haber información de cosas buenas, además de las malas noticias.
            </descripcion>
        </datosInformacion> 
    </contacto>
</contactos>

=== doriveramirez/Actividad6/casosCorrupcion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<casosCorrupcion xmlns="https://www.David.com/Politica"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="https://www.David.com/Politica Politica.xsd">
    <casoCorrupcion>
        <id>1</id>
        <datos>
            <partido>PP</partido>
            <lugar>Comunidad de Madrid</lugar>
            <costeAproximado>56000000</costeAproximado>
            <implicados>3</implicados>
            <anoHechos>2013</anoHechos>
            <estado>Abierto</estado>
        </datos>
        <informacion>
            Tres días después, Bárcenas acudió a declarar a la Fiscalía Anticorrupción 
            y negó la existencia de cuentas ocultas en el PP y que él fuera el responsable.
        </informacion>
    </casoCorrupcion>
    <casoCorrupcion>
        <id>2</id>
        <datos>
            <partido>PP-PSOE</partido>
            <lugar>Galicia</lugar>
            <costeAproximado>1882155745</costeAproximado>
            <implicados>100</implicados>
            <anoHechos>2012</anoHechos>
            <estado>Abierto</estado>
        </datos>
        <informacion>
            De Lara lo imputó en febrero de 2013 y envió la pieza a un juzgado de O Carballiño.
        </informacion>
    </casoCorrupcion>
</casosCorrupcion>
